# Source: https://github.com/davegallant/nix-config/blob/main/litellm/models/copilot.nix
# GitHub Copilot models exposed via LiteLLM.
# Refreshed via:
#   TOKEN=$(sudo cat /var/lib/litellm/.config/litellm/github_copilot/access-token)
#   curl -s https://api.githubcopilot.com/models \
#     -H "Authorization: Bearer $TOKEN" \
#     -H "Editor-Version: vscode/1.95.0" \
#     -H "Copilot-Integration-Id: vscode-chat" | jq '.data[].id'
[
  "claude-fable-5"
  "claude-opus-4.7"
  "claude-opus-4.8-fast"
  "claude-opus-4.8"
  "claude-opus-5"
  "claude-sonnet-4.6"
  "claude-sonnet-5"
  "copilot-search-a"
  "copilot-search-b"
  "copilot-search-c"
  "exec-agent-a"
  "exec-agent-b"
  "exec-agent-c"
  "gemini-3.1-pro-preview"
  "gemini-3.6-flash"
  "gemini-3.7-flash"
  "gpt-5.3-codex"
  "gpt-5.4-mini"
  "gpt-5.4"
  "gpt-5.5"
  "gpt-5.6-luna"
  "gpt-5.6-sol"
  "gpt-5.6-terra"
  "grok-4.5"
  "grok-4.6"
  "kimi-k2.7-code"
  "kimi-k3"
  "mai-code-1.1-flash"
  "mai-code-1-flash-picker"
  "trajectory-compaction"
  "gpt-5-mini"
  "gpt-4o-mini-2024-07-18"
  "gpt-4o-2024-11-20"
  "gpt-4o-2024-08-06"
  "text-embedding-3-small"
  "text-embedding-3-small-inference"
  "claude-sonnet-4.5"
  "claude-opus-4.5"
  "claude-haiku-4.5"
  "gpt-4.1-2025-04-14"
  "gpt-3.5-turbo-0613"
  "gpt-4"
  "gpt-4-0613"
  "gpt-4o-2024-05-13"
  "gpt-4-o-preview"
  "gpt-4.1"
  "gpt-3.5-turbo"
  "gpt-4o-mini"
  "gpt-4o"
  "text-embedding-ada-002"
]
