formatter = "off"
preset    = "nixos-module"
[attrs]
blank-lines = 1
merge       = true
[lets]
sort = true
[[overrides]]
attrs.first = ["flake-file", "imports", "flake", "perSystem"]
path        = "**"
[[overrides]]
attrs.first = ["includes", "nixos", "homeManager"]
path        = "den.aspects.**"
[[overrides]]
attrs.first = ["imports", "nixpkgs", "includes"]
path        = "den.aspects.*.**"
