# @generated by https://codeberg.org/goldstein/unflake
let
  deps = rec {
    unflake_github_cachix_git-hooks-nix = builtins.fetchTree {
      type = "github";
      owner = "cachix";
      repo = "git-hooks.nix";
      rev = "b68b780b69702a090c8bb1b973bab13756cc7a27";
      lastModified = 1765911976;
      narHash = "sha256-t3T/xm8zstHRLx+pIHxVpQTiySbKqcQbK+r+01XVKc0=";
    };
    unflake_github_drupol_infra-private = builtins.fetchTree {
      type = "github";
      owner = "drupol";
      repo = "infra-private";
      rev = "48ed44c8958b8ad6ff249fa11e9d20586e67edc4";
      lastModified = 1762948688;
      narHash = "sha256-VDA9YC5V1rPHkBq8ZLyyzbT7/YVTMHtIdc4UHC9u4nQ=";
    };
    unflake_github_drupol_nix-oracle-db = builtins.fetchTree {
      type = "github";
      owner = "drupol";
      repo = "nix-oracle-db";
      rev = "ed83fc92be4fc718ed2c2e2cdb9854f4f40ddb3e";
      lastModified = 1716815195;
      narHash = "sha256-c81hvKbjmqmvERZomf6QvUiyIP1ZHzzJOCdJYYzOwRs=";
    };
    unflake_github_drupol_pkgs-by-name-for-flake-parts = builtins.fetchTree {
      type = "github";
      owner = "drupol";
      repo = "pkgs-by-name-for-flake-parts";
      rev = "c5f7889af3f34825cec8d802220e766f7d52b699";
      lastModified = 1766494846;
      narHash = "sha256-5eaQ3iKcwUbLw7pOJJqV85qgf5L+ihfsISrifGM7czQ=";
    };
    unflake_github_edolstra_flake-compat = builtins.fetchTree {
      type = "github";
      owner = "edolstra";
      repo = "flake-compat";
      rev = "f275e157c50c3a9a682b4c9b4aa4db7a4cd3b5f2";
      lastModified = 1766661267;
      narHash = "sha256-QN1r/zNqvXHwWqlRAnRtFf4CQwIOJx58PtdExIzAw94=";
    };
    unflake_github_hercules-ci_flake-parts = builtins.fetchTree {
      type = "github";
      owner = "hercules-ci";
      repo = "flake-parts";
      rev = "a34fae9c08a15ad73f295041fec82323541400a9";
      lastModified = 1765835352;
      narHash = "sha256-XswHlK/Qtjasvhd1nOa1e8MgZ8GS//jBoTqWtrS1Giw=";
    };
    unflake_github_hercules-ci_gitignore-nix = builtins.fetchTree {
      type = "github";
      owner = "hercules-ci";
      repo = "gitignore.nix";
      rev = "cb5e3fdca1de58ccbc3ef53de65bd372b48f567c";
      lastModified = 1762808025;
      narHash = "sha256-XmjITeZNMTQXGhhww6ed/Wacy2KzD6svioyCX7pkUu4=";
    };
    unflake_github_nicknovitski_make-shell = builtins.fetchTree {
      type = "github";
      owner = "nicknovitski";
      repo = "make-shell";
      rev = "ffeceae9956df03571ea8e96ef77c2924f13a63c";
      lastModified = 1733933815;
      narHash = "sha256-9JjM7eT66W4NJAXpGUsdyAFXhBxFWR2Z9LZwUa7Hli0=";
    };
    unflake_github_nix-community_disko = builtins.fetchTree {
      type = "github";
      owner = "nix-community";
      repo = "disko";
      rev = "916506443ecd0d0b4a0f4cf9d40a3c22ce39b378";
      lastModified = 1766150702;
      narHash = "sha256-P0kM+5o+DKnB6raXgFEk3azw8Wqg5FL6wyl9jD+G5a4=";
    };
    unflake_github_nix-community_home-manager = builtins.fetchTree {
      type = "github";
      owner = "nix-community";
      repo = "home-manager";
      rev = "91cdb0e2d574c64fae80d221f4bf09d5592e9ec2";
      lastModified = 1766682973;
      narHash = "sha256-GKO35onS711ThCxwWcfuvbIBKXwriahGqs+WZuJ3v9E=";
    };
    unflake_github_nix-community_nixos-generators = builtins.fetchTree {
      type = "github";
      owner = "nix-community";
      repo = "nixos-generators";
      rev = "032a1878682fafe829edfcf5fdfad635a2efe748";
      lastModified = 1764234087;
      narHash = "sha256-NHF7QWa0ZPT8hsJrvijREW3+nifmF2rTXgS2v0tpcEA=";
    };
    unflake_github_nix-community_nixpkgs-lib = builtins.fetchTree {
      type = "github";
      owner = "nix-community";
      repo = "nixpkgs.lib";
      rev = "2075416fcb47225d9b68ac469a5c4801a9c4dd85";
      lastModified = 1765674936;
      narHash = "sha256-k00uTP4JNfmejrCLJOwdObYC9jHRrr/5M/a/8L2EIdo=";
    };
    unflake_github_nix-community_nur = builtins.fetchTree {
      type = "github";
      owner = "nix-community";
      repo = "nur";
      rev = "b9703c4009bae150fd5ee16fcfe33b5d1da1482f";
      lastModified = 1766691932;
      narHash = "sha256-9Z/TVjSs4Lr0gY2l1fwjOOd/hKGV9m4r6PMLFRstYjs=";
    };
    unflake_github_nix-community_plasma-manager = builtins.fetchTree {
      type = "github";
      owner = "nix-community";
      repo = "plasma-manager";
      rev = "b24ed4b272256dfc1cc2291f89a9821d5f9e14b4";
      lastModified = 1763909441;
      narHash = "sha256-56LwV51TX/FhgX+5LCG6akQ5KrOWuKgcJa+eUsRMxsc=";
    };
    unflake_github_nix-systems_default = builtins.fetchTree {
      type = "github";
      owner = "nix-systems";
      repo = "default";
      rev = "da67096a3b9bf56a91d16901293e51ba5b49a27e";
      lastModified = 1681028828;
      narHash = "sha256-Vy1rq5AaRuLzOxct8nz4T6wlgyUR7zLU309k9mBC768=";
    };
    unflake_github_nixos_nixos-hardware_ref_master = builtins.fetchTree {
      type = "github";
      owner = "nixos";
      repo = "nixos-hardware";
      rev = "c5db9569ac9cc70929c268ac461f4003e3e5ca80";
      lastModified = 1766568855;
      narHash = "sha256-UXVtN77D7pzKmzOotFTStgZBqpOcf8cO95FcupWp4Zo=";
    };
    unflake_github_nixos_nixpkgs_ref_master = builtins.fetchTree {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "709dfa4f04c825606aface1c9a56830d32521289";
      lastModified = 1766694200;
      narHash = "sha256-cYEzfa3aZR6OzgDUgIb84C1nvdEqgxM3on3l20IFBFc=";
    };
    unflake_github_nixos_nixpkgs_ref_nixos-unstable = builtins.fetchTree {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "3e2499d5539c16d0d173ba53552a4ff8547f4539";
      lastModified = 1766651565;
      narHash = "sha256-QEhk0eXgyIqTpJ/ehZKg9IKS7EtlWxF3N7DXy42zPfU=";
    };
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable = builtins.fetchTree {
      type = "github";
      owner = "nixos";
      repo = "nixpkgs";
      rev = "3c1016e6acd16ad96053116d0d3043029c9e2649";
      lastModified = 1766653575;
      narHash = "sha256-TPgxCS7+hWc4kPhzkU5dD2M5UuPhLuuaMNZ/IpwKQvI=";
    };
    unflake_github_numtide_flake-utils = builtins.fetchTree {
      type = "github";
      owner = "numtide";
      repo = "flake-utils";
      rev = "11707dc2f618dd54ca8739b309ec4fc024de578b";
      lastModified = 1731533236;
      narHash = "sha256-l0KFg5HjrsfsO/JpG+r7fRrqm12kzFHyUHqHCVpMMbI=";
    };
    unflake_github_numtide_nixos-facter-modules = builtins.fetchTree {
      type = "github";
      owner = "numtide";
      repo = "nixos-facter-modules";
      rev = "e796d536e3d83de74267069e179dc620a608ed7d";
      lastModified = 1766558141;
      narHash = "sha256-Ud9v49ZPsoDBFuyJSQ2Mpw1ZgAH/aMwUwwzrVoetNus=";
    };
    unflake_github_numtide_treefmt-nix = builtins.fetchTree {
      type = "github";
      owner = "numtide";
      repo = "treefmt-nix";
      rev = "42d96e75aa56a3f70cab7e7dc4a32868db28e8fd";
      lastModified = 1766000401;
      narHash = "sha256-+cqN4PJz9y0JQXfAK5J1drd0U05D5fcAGhzhfVrDlsI=";
    };
    unflake_github_serokell_deploy-rs = builtins.fetchTree {
      type = "github";
      owner = "serokell";
      repo = "deploy-rs";
      rev = "d5eff7f948535b9c723d60cd8239f8f11ddc90fa";
      lastModified = 1766051518;
      narHash = "sha256-znKOwPXQnt3o7lDb3hdf19oDo0BLP4MfBOYiWkEHoik=";
    };
    unflake_github_tlater_nix-webapps = builtins.fetchTree {
      type = "github";
      owner = "tlater";
      repo = "nix-webapps";
      rev = "1bb9ee8e3f428575c1c6898ae7af8d96416d696a";
      lastModified = 1734815698;
      narHash = "sha256-dH1QJJ5TyPVH9kvvGsHufwY0evWeayaaUl/Ge3X3OYs=";
    };
    unflake_github_vic_import-tree = builtins.fetchTree {
      type = "github";
      owner = "vic";
      repo = "import-tree";
      rev = "3c23749d8013ec6daa1d7255057590e9ca726646";
      lastModified = 1763762820;
      narHash = "sha256-ZvYKbFib3AEwiNMLsejb/CWs/OL/srFQ8AogkebEPF0=";
    };
    unflake_sourcehut_-rycee_lazy-apps = builtins.fetchTree {
      type = "sourcehut";
      owner = "~rycee";
      repo = "lazy-apps";
      rev = "4ddc92c77213f8ed3ddef1868f4a19002afa728a";
      lastModified = 1764660538;
      narHash = "sha256-kEWb9Hc2OxdLhJ1pRdW7zRZ57Mul3/Jpy3vyhQ8Yq6o=";
    };
    unflake_git_https---codeberg-org-FrdrCkII-falake-git = builtins.fetchTree {
      type = "git";
      url = "https://codeberg.org/FrdrCkII/falake.git";
      rev = "1864d0f714f059cf9975f88ee3aaada57415e6f9";
      revCount = 23;
      lastModified = 1766565676;
      narHash = "sha256-gj8NQChRpH6sIAXT3R9xOcFvyxd9YQ1PCofkBBUDIuE=";
    };
    unflake_github_edolstra_flake-compat_flake_false = unflake_github_edolstra_flake-compat;
  };
  universe = rec {
    unflake_github_cachix_git-hooks-nix =
      ((import "${deps.unflake_github_cachix_git-hooks-nix.outPath}/flake.nix").outputs {
        self = unflake_github_cachix_git-hooks-nix;
        flake-compat = unflake_github_edolstra_flake-compat_flake_false;
        gitignore = unflake_github_hercules-ci_gitignore-nix;
        nixpkgs = unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
      })
      // deps.unflake_github_cachix_git-hooks-nix
      // {
        _flake = true;
        outPath = "${deps.unflake_github_cachix_git-hooks-nix.outPath}";
        sourceInfo = deps.unflake_github_cachix_git-hooks-nix;
      };
    unflake_github_drupol_infra-private =
      ((import "${deps.unflake_github_drupol_infra-private.outPath}/flake.nix").outputs {
        self = unflake_github_drupol_infra-private;
        flake-parts = unflake_github_hercules-ci_flake-parts;
        home-manager = unflake_github_nix-community_home-manager;
        import-tree = unflake_github_vic_import-tree;
        nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
        nixpkgs-master = unflake_github_nixos_nixpkgs_ref_master;
        nixpkgs-unstable = unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
        systems = unflake_github_nix-systems_default;
      })
      // deps.unflake_github_drupol_infra-private
      // {
        _flake = true;
        outPath = "${deps.unflake_github_drupol_infra-private.outPath}";
        sourceInfo = deps.unflake_github_drupol_infra-private;
      };
    unflake_github_drupol_nix-oracle-db =
      ((import "${deps.unflake_github_drupol_nix-oracle-db.outPath}/flake.nix").outputs {
        self = unflake_github_drupol_nix-oracle-db;
        nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
        systems = unflake_github_nix-systems_default;
      })
      // deps.unflake_github_drupol_nix-oracle-db
      // {
        _flake = true;
        outPath = "${deps.unflake_github_drupol_nix-oracle-db.outPath}";
        sourceInfo = deps.unflake_github_drupol_nix-oracle-db;
      };
    unflake_github_drupol_pkgs-by-name-for-flake-parts =
      ((import "${deps.unflake_github_drupol_pkgs-by-name-for-flake-parts.outPath}/flake.nix").outputs {
        self = unflake_github_drupol_pkgs-by-name-for-flake-parts;
      })
      // deps.unflake_github_drupol_pkgs-by-name-for-flake-parts
      // {
        _flake = true;
        outPath = "${deps.unflake_github_drupol_pkgs-by-name-for-flake-parts.outPath}";
        sourceInfo = deps.unflake_github_drupol_pkgs-by-name-for-flake-parts;
      };
    inherit (deps) unflake_github_edolstra_flake-compat_flake_false;
    unflake_github_hercules-ci_flake-parts =
      ((import "${deps.unflake_github_hercules-ci_flake-parts.outPath}/flake.nix").outputs {
        self = unflake_github_hercules-ci_flake-parts;
        nixpkgs-lib = unflake_github_nix-community_nixpkgs-lib;
      })
      // deps.unflake_github_hercules-ci_flake-parts
      // {
        _flake = true;
        outPath = "${deps.unflake_github_hercules-ci_flake-parts.outPath}";
        sourceInfo = deps.unflake_github_hercules-ci_flake-parts;
      };
    unflake_github_hercules-ci_gitignore-nix =
      ((import "${deps.unflake_github_hercules-ci_gitignore-nix.outPath}/flake.nix").outputs {
        self = unflake_github_hercules-ci_gitignore-nix;
      })
      // deps.unflake_github_hercules-ci_gitignore-nix
      // {
        _flake = true;
        outPath = "${deps.unflake_github_hercules-ci_gitignore-nix.outPath}";
        sourceInfo = deps.unflake_github_hercules-ci_gitignore-nix;
      };
    unflake_github_nicknovitski_make-shell =
      ((import "${deps.unflake_github_nicknovitski_make-shell.outPath}/flake.nix").outputs {
        self = unflake_github_nicknovitski_make-shell;
        flake-compat = unflake_github_edolstra_flake-compat_flake_false;
      })
      // deps.unflake_github_nicknovitski_make-shell
      // {
        _flake = true;
        outPath = "${deps.unflake_github_nicknovitski_make-shell.outPath}";
        sourceInfo = deps.unflake_github_nicknovitski_make-shell;
      };
    unflake_github_nix-community_disko =
      ((import "${deps.unflake_github_nix-community_disko.outPath}/flake.nix").outputs {
        self = unflake_github_nix-community_disko;
        nixpkgs = unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
      })
      // deps.unflake_github_nix-community_disko
      // {
        _flake = true;
        outPath = "${deps.unflake_github_nix-community_disko.outPath}";
        sourceInfo = deps.unflake_github_nix-community_disko;
      };
    unflake_github_nix-community_home-manager =
      ((import "${deps.unflake_github_nix-community_home-manager.outPath}/flake.nix").outputs {
        self = unflake_github_nix-community_home-manager;
        nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
      })
      // deps.unflake_github_nix-community_home-manager
      // {
        _flake = true;
        outPath = "${deps.unflake_github_nix-community_home-manager.outPath}";
        sourceInfo = deps.unflake_github_nix-community_home-manager;
      };
    unflake_github_nix-community_nixos-generators =
      ((import "${deps.unflake_github_nix-community_nixos-generators.outPath}/flake.nix").outputs {
        self = unflake_github_nix-community_nixos-generators;
        nixlib = unflake_github_nix-community_nixpkgs-lib;
        nixpkgs = unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
      })
      // deps.unflake_github_nix-community_nixos-generators
      // {
        _flake = true;
        outPath = "${deps.unflake_github_nix-community_nixos-generators.outPath}";
        sourceInfo = deps.unflake_github_nix-community_nixos-generators;
      };
    unflake_github_nix-community_nixpkgs-lib =
      ((import "${deps.unflake_github_nix-community_nixpkgs-lib.outPath}/flake.nix").outputs {
        self = unflake_github_nix-community_nixpkgs-lib;
      })
      // deps.unflake_github_nix-community_nixpkgs-lib
      // {
        _flake = true;
        outPath = "${deps.unflake_github_nix-community_nixpkgs-lib.outPath}";
        sourceInfo = deps.unflake_github_nix-community_nixpkgs-lib;
      };
    unflake_github_nix-community_nur =
      ((import "${deps.unflake_github_nix-community_nur.outPath}/flake.nix").outputs {
        self = unflake_github_nix-community_nur;
        flake-parts = unflake_github_hercules-ci_flake-parts;
        nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
      })
      // deps.unflake_github_nix-community_nur
      // {
        _flake = true;
        outPath = "${deps.unflake_github_nix-community_nur.outPath}";
        sourceInfo = deps.unflake_github_nix-community_nur;
      };
    unflake_github_nix-community_plasma-manager =
      ((import "${deps.unflake_github_nix-community_plasma-manager.outPath}/flake.nix").outputs {
        self = unflake_github_nix-community_plasma-manager;
        home-manager = unflake_github_nix-community_home-manager;
        nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
      })
      // deps.unflake_github_nix-community_plasma-manager
      // {
        _flake = true;
        outPath = "${deps.unflake_github_nix-community_plasma-manager.outPath}";
        sourceInfo = deps.unflake_github_nix-community_plasma-manager;
      };
    unflake_github_nix-systems_default =
      ((import "${deps.unflake_github_nix-systems_default.outPath}/flake.nix").outputs {
        self = unflake_github_nix-systems_default;
      })
      // deps.unflake_github_nix-systems_default
      // {
        _flake = true;
        outPath = "${deps.unflake_github_nix-systems_default.outPath}";
        sourceInfo = deps.unflake_github_nix-systems_default;
      };
    unflake_github_nixos_nixos-hardware_ref_master =
      ((import "${deps.unflake_github_nixos_nixos-hardware_ref_master.outPath}/flake.nix").outputs {
        self = unflake_github_nixos_nixos-hardware_ref_master;
      })
      // deps.unflake_github_nixos_nixos-hardware_ref_master
      // {
        _flake = true;
        outPath = "${deps.unflake_github_nixos_nixos-hardware_ref_master.outPath}";
        sourceInfo = deps.unflake_github_nixos_nixos-hardware_ref_master;
      };
    unflake_github_nixos_nixpkgs_ref_master =
      ((import "${deps.unflake_github_nixos_nixpkgs_ref_master.outPath}/flake.nix").outputs {
        self = unflake_github_nixos_nixpkgs_ref_master;
      })
      // deps.unflake_github_nixos_nixpkgs_ref_master
      // {
        _flake = true;
        outPath = "${deps.unflake_github_nixos_nixpkgs_ref_master.outPath}";
        sourceInfo = deps.unflake_github_nixos_nixpkgs_ref_master;
      };
    unflake_github_nixos_nixpkgs_ref_nixos-unstable =
      ((import "${deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable.outPath}/flake.nix").outputs {
        self = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
      })
      // deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable
      // {
        _flake = true;
        outPath = "${deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable.outPath}";
        sourceInfo = deps.unflake_github_nixos_nixpkgs_ref_nixos-unstable;
      };
    unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable =
      ((import "${deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable.outPath}/flake.nix").outputs {
        self = unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
      })
      // deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable
      // {
        _flake = true;
        outPath = "${deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable.outPath}";
        sourceInfo = deps.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
      };
    unflake_github_numtide_flake-utils =
      ((import "${deps.unflake_github_numtide_flake-utils.outPath}/flake.nix").outputs {
        self = unflake_github_numtide_flake-utils;
        systems = unflake_github_nix-systems_default;
      })
      // deps.unflake_github_numtide_flake-utils
      // {
        _flake = true;
        outPath = "${deps.unflake_github_numtide_flake-utils.outPath}";
        sourceInfo = deps.unflake_github_numtide_flake-utils;
      };
    unflake_github_numtide_nixos-facter-modules =
      ((import "${deps.unflake_github_numtide_nixos-facter-modules.outPath}/flake.nix").outputs {
        self = unflake_github_numtide_nixos-facter-modules;
      })
      // deps.unflake_github_numtide_nixos-facter-modules
      // {
        _flake = true;
        outPath = "${deps.unflake_github_numtide_nixos-facter-modules.outPath}";
        sourceInfo = deps.unflake_github_numtide_nixos-facter-modules;
      };
    unflake_github_numtide_treefmt-nix =
      ((import "${deps.unflake_github_numtide_treefmt-nix.outPath}/flake.nix").outputs {
        self = unflake_github_numtide_treefmt-nix;
        nixpkgs = unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
      })
      // deps.unflake_github_numtide_treefmt-nix
      // {
        _flake = true;
        outPath = "${deps.unflake_github_numtide_treefmt-nix.outPath}";
        sourceInfo = deps.unflake_github_numtide_treefmt-nix;
      };
    unflake_github_serokell_deploy-rs =
      ((import "${deps.unflake_github_serokell_deploy-rs.outPath}/flake.nix").outputs {
        self = unflake_github_serokell_deploy-rs;
        flake-compat = unflake_github_edolstra_flake-compat_flake_false;
        nixpkgs = unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
        utils = unflake_github_numtide_flake-utils;
      })
      // deps.unflake_github_serokell_deploy-rs
      // {
        _flake = true;
        outPath = "${deps.unflake_github_serokell_deploy-rs.outPath}";
        sourceInfo = deps.unflake_github_serokell_deploy-rs;
      };
    unflake_github_tlater_nix-webapps =
      ((import "${deps.unflake_github_tlater_nix-webapps.outPath}/flake.nix").outputs {
        self = unflake_github_tlater_nix-webapps;
        flake-parts = unflake_github_hercules-ci_flake-parts;
        nixpkgs = unflake_github_nixos_nixpkgs_ref_nixos-unstable;
        pkgs-by-name-for-flake-parts = unflake_github_drupol_pkgs-by-name-for-flake-parts;
        systems = unflake_github_nix-systems_default;
      })
      // deps.unflake_github_tlater_nix-webapps
      // {
        _flake = true;
        outPath = "${deps.unflake_github_tlater_nix-webapps.outPath}";
        sourceInfo = deps.unflake_github_tlater_nix-webapps;
      };
    unflake_github_vic_import-tree =
      ((import "${deps.unflake_github_vic_import-tree.outPath}/flake.nix").outputs {
        self = unflake_github_vic_import-tree;
      })
      // deps.unflake_github_vic_import-tree
      // {
        _flake = true;
        outPath = "${deps.unflake_github_vic_import-tree.outPath}";
        sourceInfo = deps.unflake_github_vic_import-tree;
      };
    unflake_sourcehut_-rycee_lazy-apps =
      ((import "${deps.unflake_sourcehut_-rycee_lazy-apps.outPath}/flake.nix").outputs {
        self = unflake_sourcehut_-rycee_lazy-apps;
        nixpkgs = unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
        pre-commit-hooks = unflake_github_cachix_git-hooks-nix;
      })
      // deps.unflake_sourcehut_-rycee_lazy-apps
      // {
        _flake = true;
        outPath = "${deps.unflake_sourcehut_-rycee_lazy-apps.outPath}";
        sourceInfo = deps.unflake_sourcehut_-rycee_lazy-apps;
      };
    unflake_git_https---codeberg-org-FrdrCkII-falake-git =
      ((import "${deps.unflake_git_https---codeberg-org-FrdrCkII-falake-git.outPath}/flake.nix").outputs {
        self = unflake_git_https---codeberg-org-FrdrCkII-falake-git;
      })
      // deps.unflake_git_https---codeberg-org-FrdrCkII-falake-git
      // {
        _flake = true;
        outPath = "${deps.unflake_git_https---codeberg-org-FrdrCkII-falake-git.outPath}";
        sourceInfo = deps.unflake_git_https---codeberg-org-FrdrCkII-falake-git;
      };
  };
  inputs = {
    deploy-rs = universe.unflake_github_serokell_deploy-rs;
    disko = universe.unflake_github_nix-community_disko;
    falake = universe.unflake_git_https---codeberg-org-FrdrCkII-falake-git;
    git-hooks = universe.unflake_github_cachix_git-hooks-nix;
    home-manager = universe.unflake_github_nix-community_home-manager;
    import-tree = universe.unflake_github_vic_import-tree;
    infra-private = universe.unflake_github_drupol_infra-private;
    lazy-apps = universe.unflake_sourcehut_-rycee_lazy-apps;
    make-shell = universe.unflake_github_nicknovitski_make-shell;
    nix-oracle-db = universe.unflake_github_drupol_nix-oracle-db;
    nix-webapps = universe.unflake_github_tlater_nix-webapps;
    nixos-facter-modules = universe.unflake_github_numtide_nixos-facter-modules;
    nixos-generators = universe.unflake_github_nix-community_nixos-generators;
    nixos-hardware = universe.unflake_github_nixos_nixos-hardware_ref_master;
    nixpkgs = universe.unflake_github_nixos_nixpkgs_ref_nixos-unstable;
    nixpkgs-master = universe.unflake_github_nixos_nixpkgs_ref_master;
    nixpkgs-unstable = universe.unflake_github_nixos_nixpkgs_ref_nixpkgs-unstable;
    nur = universe.unflake_github_nix-community_nur;
    pkgs-by-name-for-flake-parts = universe.unflake_github_drupol_pkgs-by-name-for-flake-parts;
    plasma-manager = universe.unflake_github_nix-community_plasma-manager;
    systems = universe.unflake_github_nix-systems_default;
    treefmt-nix = universe.unflake_github_numtide_treefmt-nix;
    self = throw "to use inputs.self, write `import ./unflake.nix (inputs: ...)`";
    withInputs =
      outputs:
      let
        self = outputs (inputs // { inherit self; });
      in
      self;
    __functor = self: self.withInputs;
  };
in
inputs
