prSections:
- title: PR to review
  filters: "repo:NixOS/nixpkgs is:open draft:false -author:r-ryantm"
- title: First time contribution PRs
  filters: repo:NixOS/nixpkgs is:open draft:false label:"12. first-time contribution"
- title: PRs with only 1 approvals
  filters: "repo:NixOS/nixpkgs is:open draft:false label:\"12.approvals: 1\""
- title: PRs from r-ryantm
  filters: "repo:NixOS/nixpkgs is:open draft:false author:r-ryantm"
- title: My Pull Requests
  filters: is:open author:@me
- title: Needs My Review
  filters: is:open review-requested:@me
- title: Involved
  filters: is:open involves:@me -author:@me
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 50
  issuesLimit: 50
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  prs: []
  prs:
    - key: v
      command: >
        cd {{.RepoPath}} &&
        code . &&
        gh pr checkout {{.PrNumber}}
repoPaths:
  NixOS/*: ~/Code/NixOS/*
theme:
  ui:
    table:
      showSeparator: true
pager:
  diff: ""
