[revset-aliases]
"/" = "trunk()"
"_" = "fork_point(trunk() | @)"
"_(x)" = "fork_point(trunk() | x)"
'base_point(x)' = "heads(immutable_heads() & ::x)"
custom_log = '''none()
  | base_point(@)
  | ancestors(@, 10) & trunk()..@
  | trunk()
  | bookmarks()
  | mutable() & visible_heads()
  | fork_point(mutable() & visible_heads())
  | (mutable() & merges())-
'''
"mine()" = "author(exact:'@name@') | author(exact:'@email@')"
"open()" = "stack(trunk().. & mine(), 2)"
"open(n)" = "stack(trunk().. & mine(), n)"
"private()" = "description(glob:'private:*')"
safe_heads = "remote_bookmarks()"
"stack()" = "stack(@, 2)"
"stack(x)" = "stack(x, 2)"
"stack(x, n)" = "ancestors(reachable(x, mutable()), n)"
"streams()" = "heads(::@ & bookmarks())"
"streams(x)" = "heads(::x & bookmarks())"
'why_immutable(r)' = '(r & immutable()) | roots(r:: & immutable_heads())'
"wip()" = "description(glob:'wip:*')"
