name: "Auto update flake lock file"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 0"
jobs:
  update-flake-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@main
      - uses: cachix/install-nix-action@v31
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Run script
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          nix run .#gh-flake-update -- \
            --assignee drupol \
            --reviewer drupol \
            nixosConfigurations.x13.config.system.build.toplevel \
            nixosConfigurations.xeonixos.config.system.build.toplevel
