name: Check

on:
  pull_request:
  push:
    paths:
    - '**.nix'
    - flake.lock
    - .github/workflows/*.yaml

jobs:
  build:
    name: 'Flake check'
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5

      - name: Run nix flake check
        run: nix flake check --no-build
