name: Check

on:
  pull_request:
  push:
    paths:
    - '**.nix'
    - flake.lock
    - .github/workflows/*.yaml

jobs:
  build:
    name: 'Flake check'
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install Lix
        run: |
          curl -sSf -L https://install.lix.systems/lix | sh -s -- install --no-confirm
          echo "trusted-users = root runner" | sudo tee -a /etc/nix/nix.conf
          echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
          sudo systemctl restart nix-daemon

      - name: Run nix flake check
        run: nix flake check --no-build
