name: 'Update flakes'

on:
  workflow_dispatch:
  schedule:
    - cron: '51 2 * * 0'

jobs:
  createPullRequest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Make changes to pull request
        run: nix flake update --recreate-lock-file

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'flake: Update dependencies'
          committer: 'GitHub <noreply@github.com>'
          author: '${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>'
          signoff: false
          branch: flake-updates
          delete-branch: true
          title: 'Upgrade flakes'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request

      - name: Check outputs
        run: |
          echo 'Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}'
          echo 'Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}'
