name: 'Update flakes'

on:
  workflow_dispatch:
  schedule:
    - cron: '51 2 * * 0'

jobs:
  createPullRequest:
    runs-on: ubuntu-20.04

    steps:
      - name: Set git to use LF
        run: |
            git config --global core.autocrlf false
            git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
            fetch-depth: 1

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.5pre20211026_5667822/install
          # Configure Nix to enable flakes
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run the general flake checks
        run: nix flake check

      - name: Make changes to pull request
        run: nix flake update

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'flake: Update dependencies'
          committer: 'GitHub <noreply@github.com>'
          author: '${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>'
          signoff: false
          branch: flake-updates
          delete-branch: true
          title: 'Upgrade flakes'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request

      - name: Check outputs
        run: |
          echo 'Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}'
          echo 'Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}'
