name: 'Update flake lock file'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  createPullRequest:
    runs-on: ubuntu-20.04

    steps:
      - name: Set git to use LF
        run: |
            git config --global core.autocrlf false
            git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
            fetch-depth: 1

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v3